### ISSUE TITLE
Create `ModularBehaviorPlatform` package

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/Bonsai.AllenNeuralDynamics#30]
As VrForaging matures and the next tasks begin to take form, we should move all the primitives currently kept in the extensions folder of the Vrforaging task to a centralized package to be re-used across tasks.

What should we name this package?
 - ModularBehaviorPlatform
 - MultiTaskPlatform

**Comment by cindypoo** [comment]
I like MultiTask because its is explicit and highlights how this is different than others.
Modular does not necessary mean multitask

**Comment by cindypoo** [comment]
Or maybe combine the two "ModularMultiTaskPlatform"
